Refactored
r0x0r/pywebview pull request #1153
Opened 2023-06-12 06:24 UTC by LopeKinz

NEVER MERGE INTO MAIN BRANCH!
This Refactor was done by Sourcery AI.

Refactor was done to save Space, Resources and make the code more Readable.

STATS:
23 Files changed
139 additions and 170 deletions.

2023-06-12 06:28 UTC, LopeKinz commented
AppVeyor Build falied due to older Python Version. This refactor is for python 3.8 or higher

2023-06-14 12:46 UTC, baseplate-admin requested changes
Hi, can we do these changes please ?

2023-06-14 12:46 UTC, baseplate-admin commented on examples/flask_app/src/backend/app.py
> -    # do whatever you need to do
let's keep this comment

2023-06-14 12:46 UTC, baseplate-admin commented on examples/flask_app/src/backend/server.py
> +    )
Old version looks more readable to me :)

2023-06-14 13:03 UTC, LopeKinz commented
Changes in progress

2023-06-14 13:13 UTC, LopeKinz commented
changed!

2023-06-14 13:15 UTC, baseplate-admin commented
Maybe we should remove python 3.7 support and move to python 3.8+

2023-06-28 20:53 UTC, r0x0r commented
This refactoring is a mixed bag imo. Some parts are more readable, others not so much. I prefer simple code over compact one-liners.
@LopeKinz if you feel like making manual changes, I can go through this PR.

2023-07-03 01:30 UTC, baseplate-admin commented
Note that this PR will also effectively require us to use python 3.8 as the minimum version

2023-08-07 02:20 UTC, closed without merging